export enum LanguageTier {
  TIER_1 = "TIER_1",
  TIER_2 = "TIER_2",
  TIER_3 = "TIER_3",
}

export interface LanguageMetadata {
  code: string;
  bcp47: string;
  name_en: string;
  name_native: string;
  tier: LanguageTier;
  supports_stt: boolean;
  supports_nmt: boolean;
  supports_tts: boolean;
  supports_voice_clone: boolean;
}

export const SUPPORTED_LANGUAGES: Record<string, LanguageMetadata> = {
  eng: {
    code: "eng",
    bcp47: "en-US",
    name_en: "English",
    name_native: "English",
    tier: LanguageTier.TIER_1,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  spa: {
    code: "spa",
    bcp47: "es-ES",
    name_en: "Spanish",
    name_native: "Español",
    tier: LanguageTier.TIER_1,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  fra: {
    code: "fra",
    bcp47: "fr-FR",
    name_en: "French",
    name_native: "Français",
    tier: LanguageTier.TIER_1,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  deu: {
    code: "deu",
    bcp47: "de-DE",
    name_en: "German",
    name_native: "Deutsch",
    tier: LanguageTier.TIER_1,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  zho: {
    code: "zho",
    bcp47: "zh-CN",
    name_en: "Mandarin Chinese",
    name_native: "中文",
    tier: LanguageTier.TIER_1,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  jpn: {
    code: "jpn",
    bcp47: "ja-JP",
    name_en: "Japanese",
    name_native: "日本語",
    tier: LanguageTier.TIER_1,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  hin: {
    code: "hin",
    bcp47: "hi-IN",
    name_en: "Hindi",
    name_native: "हिन्दी",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  por: {
    code: "por",
    bcp47: "pt-BR",
    name_en: "Portuguese",
    name_native: "Português",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  ara: {
    code: "ara",
    bcp47: "ar-SA",
    name_en: "Arabic",
    name_native: "العربية",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  rus: {
    code: "rus",
    bcp47: "ru-RU",
    name_en: "Russian",
    name_native: "Русский",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  ita: {
    code: "ita",
    bcp47: "it-IT",
    name_en: "Italian",
    name_native: "Italiano",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  kor: {
    code: "kor",
    bcp47: "ko-KR",
    name_en: "Korean",
    name_native: "한국어",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  tur: {
    code: "tur",
    bcp47: "tr-TR",
    name_en: "Turkish",
    name_native: "Türkçe",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  nld: {
    code: "nld",
    bcp47: "nl-NL",
    name_en: "Dutch",
    name_native: "Nederlands",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  pol: {
    code: "pol",
    bcp47: "pl-PL",
    name_en: "Polish",
    name_native: "Polski",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  swe: {
    code: "swe",
    bcp47: "sv-SE",
    name_en: "Swedish",
    name_native: "Svenska",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  vie: {
    code: "vie",
    bcp47: "vi-VN",
    name_en: "Vietnamese",
    name_native: "Tiếng Việt",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
  ind: {
    code: "ind",
    bcp47: "id-ID",
    name_en: "Indonesian",
    name_native: "Bahasa Indonesia",
    tier: LanguageTier.TIER_2,
    supports_stt: true,
    supports_nmt: true,
    supports_tts: true,
    supports_voice_clone: true,
  },
};

export function getLanguage(code: string): LanguageMetadata | undefined {
  return SUPPORTED_LANGUAGES[code.toLowerCase().trim()];
}

export function isLanguageSupported(code: string): boolean {
  return code.toLowerCase().trim() in SUPPORTED_LANGUAGES;
}
