"""Assistant Worker Data Models and Result Types adhering to Document 14."""

from dataclasses import dataclass, field

import numpy as np


@dataclass(frozen=True)
class IndexedSegment:
    """Represents a transcript segment stored in the vector index for RAG."""

    source_segment_id: str
    text: str
    speaker_name: str | None = None
    embedding: np.ndarray = field(default_factory=lambda: np.empty(0, dtype=np.float32))
    timestamp_ms: int = 0
    meeting_id: str = ""
    tenant_id: str = ""


@dataclass(frozen=True)
class AssistantAnswer:
    """Represents a grounded natural language response generated by the assistant."""

    query_id: str
    answer: str
    citations: list[str] = field(default_factory=list)
    action_items: list[str] = field(default_factory=list)
    confidence: float = 1.0
    latency_ms: int = 0


@dataclass(frozen=True)
class MeetingSummary:
    """Represents an extracted executive summary of a meeting session."""

    meeting_id: str
    summary: str
    action_items: list[str] = field(default_factory=list)
    key_decisions: list[str] = field(default_factory=list)
    topics: list[str] = field(default_factory=list)
