export enum ParticipantRole {
  HOST = "HOST",
  MODERATOR = "MODERATOR",
  PARTICIPANT = "PARTICIPANT",
  GUEST = "GUEST",
}

export enum MeetingStatus {
  SCHEDULED = "SCHEDULED",
  ACTIVE = "ACTIVE",
  ENDED = "ENDED",
  ARCHIVED = "ARCHIVED",
}

export enum AudioStreamType {
  ORIGINAL_HUMAN = "ORIGINAL_HUMAN",
  TRANSLATED_SYNTHETIC = "TRANSLATED_SYNTHETIC",
}

export enum TranscriptFormat {
  JSON = "JSON",
  SRT = "SRT",
  VTT = "VTT",
  TXT = "TXT",
}

export enum WSClientMessageType {
  JOIN = "JOIN",
  SET_LISTENING_LANGUAGE = "SET_LISTENING_LANGUAGE",
  CHAT_MESSAGE = "CHAT_MESSAGE",
  QUERY_ASSISTANT = "QUERY_ASSISTANT",
  PING = "PING",
}

export enum WSServerMessageType {
  ROOM_STATE = "ROOM_STATE",
  PARTICIPANT_JOINED = "PARTICIPANT_JOINED",
  PARTICIPANT_LEFT = "PARTICIPANT_LEFT",
  CAPTION_UPDATE = "CAPTION_UPDATE",
  AUDIO_TRACK_PUBLISHED = "AUDIO_TRACK_PUBLISHED",
  ASSISTANT_RESPONSE = "ASSISTANT_RESPONSE",
  PONG = "PONG",
  ERROR = "ERROR",
}
